'use strict'

// REGEX 
const EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;


const MAX_LENGTH_NAME = 150
// USER
const MAX_LOGIN_INCORRECT = 5

// SHOP
const SHOP_MANAGER = 1111
const SHOP_COLLABORATOR = 2222
const MAX_STAFF = 4

const SHOP_ACTIVE = 'active'
const SHOP_INACTIVE = 'inactive'

const USER_ACTIVE = 'active'
const USER_BE_BANED = 'baned'

// DISCOUNT
const DISCOUNT_PERCENT = 'percent'
const DISCOUNT_FIXED_AMOUNT = 'fixedAmount'
const DISCOUNT_APPLY_ALL = 'all'
const DISCOUNT_APPLY_SPECIFIC = 'specific'

// DISCOUNT
const DISCOUNT_TYPES = [
    DISCOUNT_PERCENT,
    DISCOUNT_FIXED_AMOUNT
]


// CARTS 
const CART_STATE_ACTIVE = 'active'
const CART_STATE_PENDING = 'pending'

const CART_STATES = [ 
    CART_STATE_ACTIVE,
    CART_STATE_PENDING
]

// ODER
const PAYMENT_METHOD_CARD = 'CARD'
const PAYMENT_METHOD_INTERNET_BANK = 'INTER_BANK'
const PAYMENT_METHOD_COD = 'COD'

const PAYMENT_STATUS_UNPAID = 1
const PAYMENT_STATUS_PAID = 2
const PAYMENT_STATUS_VERIFIED = 3
const PAYMENT_STATUS_CANCEL = 0

const ORDER_STATUS_PENDING = 1
const ORDER_STATUS_VERIFIED = 2
const ORDER_STATUS_DELIVERY = 3
const ORDER_STATUS_COMPLETED = 4

const ORDER_STATUS = [
    ORDER_STATUS_PENDING,
    ORDER_STATUS_VERIFIED,
    ORDER_STATUS_DELIVERY,
    ORDER_STATUS_COMPLETED
]

const PAYMENT_STATUS = [
    PAYMENT_STATUS_UNPAID,
    PAYMENT_STATUS_PAID,
    PAYMENT_STATUS_VERIFIED,
    PAYMENT_STATUS_CANCEL,
]

const PAYMENT_METHODS = [
    PAYMENT_METHOD_CARD,
    PAYMENT_METHOD_INTERNET_BANK,
    PAYMENT_METHOD_COD
]

// PRODUCT
const CLOTHING_PRODUCT = 'Clothing'
const ELECTRONIC_PRODUCT = 'Electronics'
const FURNITURE_PRODUCT = 'Furniture'

const CATEGORY_LIST = [
    CLOTHING_PRODUCT,
    ELECTRONIC_PRODUCT,
    FURNITURE_PRODUCT,
]

// USER_ADDRESS 
const ADDRESS_HOME = 'home'
const ADDRESS_WORK = 'work'
const ADDRESS_OTHER = 'other'

const DEFAULT_COUNTRY = 'VN'

const USER_ADDRESSES = [
    ADDRESS_HOME,
    ADDRESS_WORK,
    ADDRESS_OTHER
]

// API KEY
const FULL_PER = '0000'
const WRITE_PER = '1111'
const DELETE_PER = '0000'

const PERMISSIONS = [
    FULL_PER,
    WRITE_PER,
    DELETE_PER
]

// INVENTORY 
const INVENTORY_IN_STOCK = 'in stock'
const INVENTORY_OUT_OF_STOCK = 'out of stock'
const INVENTORY_LOW_STOCK = 'low stock'

const INVENTORY_ACTION_EXPORT = 'export'
const INVENTORY_ACTION_IMPORT = 'import'

const INVENTORY_STATUS = [
    INVENTORY_IN_STOCK,
    INVENTORY_OUT_OF_STOCK,
    INVENTORY_LOW_STOCK
]

const INVENTORY_ACTION = [
    INVENTORY_ACTION_EXPORT,
    INVENTORY_ACTION_IMPORT
]

// AUTH 
const HEADER = {
    API_KEY: 'x-api-key',
    AUTHORIZATION: 'authorization',
    REFRESHTOKEN: 'x-rtoken-id'
}

module.exports = {
    HEADER,
    MAX_LENGTH_NAME,
    SHOP_ACTIVE, 
    SHOP_INACTIVE,
    USER_ACTIVE,
    USER_BE_BANED,
    CATEGORY_LIST,
    DISCOUNT_TYPES,
    DISCOUNT_APPLY_ALL,
    DISCOUNT_APPLY_SPECIFIC,
    DISCOUNT_PERCENT,
    DISCOUNT_FIXED_AMOUNT,
    CART_STATES,
    PAYMENT_METHODS,
    PAYMENT_METHOD_INTERNET_BANK,
    PAYMENT_METHOD_CARD,
    PAYMENT_METHOD_COD,
    SHOP_MANAGER,
    SHOP_COLLABORATOR,
    PAYMENT_STATUS,
    PAYMENT_STATUS_UNPAID,
    PAYMENT_STATUS_PAID,
    PAYMENT_STATUS_VERIFIED,
    PAYMENT_STATUS_CANCEL,
    ORDER_STATUS,
    ORDER_STATUS_PENDING,
    ORDER_STATUS_VERIFIED,
    ORDER_STATUS_DELIVERY,
    ORDER_STATUS_COMPLETED,
    PERMISSIONS,
    INVENTORY_STATUS,
    INVENTORY_IN_STOCK,
    INVENTORY_OUT_OF_STOCK,
    INVENTORY_LOW_STOCK,
    INVENTORY_ACTION,
    INVENTORY_ACTION_EXPORT,
    INVENTORY_ACTION_IMPORT,
    MAX_LOGIN_INCORRECT,
    FULL_PER,
    WRITE_PER,
    DELETE_PER,
    EMAIL_REGEX,
    MAX_STAFF,
    CLOTHING_PRODUCT,
    ELECTRONIC_PRODUCT,
    FURNITURE_PRODUCT,
    CART_STATE_ACTIVE,
    CART_STATE_PENDING
}
